steps:
  # Build and Push User-Location Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/apphub/user-location:latest', './user-location']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/apphub/user-location:latest']

  # Build and Push OTel Collector Sidecar Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/apphub/otel-collector:latest', './otel-collector']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/apphub/otel-collector:latest']

  # Build and Push Web Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/apphub/web:latest', './web']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/apphub/web:latest']

substitutions:
  _REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY
